CREATE VIEW EMPLOYEE_DGROUP AS
SELECT HRD.EMPLOYEE.ISMEDI, HRD.EMPLOYEE.ISSPE, HRD.EMPLOYEE.ISENT, HRD.EMPLOYEE.ISPERSO,
HRD.EMPLOYEE.ISNIGHT,HRD.EMPLOYEE.BSAL, HRD.EMPLOYEE.ISOVT, HRD.EMPLOYEE.ISBONUS,
HRD.EMPLOYEE.ISPHONE, HRD.EMPLOYEE.ISTRANS, HRD.EMPLOYEE.ISRESI, HRD.EMPLOYEE.ISCONVEY,
HRD.SALARY.ABS_FROM_DATE,HRD.SALARY.ABS_TO_DATE,
HRD.EMPLOYEE.ISINSUR, HRD.EMPLOYEE.ISPF, HRD.EMPLOYEE.ISOUT,
HRD.EMPLOYEE.SECTID, HRD.EMPLOYEE.DEPTID, HRD.EMPLOYEE.DESIGID, HRD.EMPLOYEE.EMPID,
HRD.EMPLOYEE.EMPSTAT, HRD.EMPLOYEE.DOLINCR, HRD.DGROUP.WATER,
HRD.DGROUP.SWE, HRD.DGROUP.PFIR, HRD.DGROUP.GROUPID, HRD.DGROUP.HRR, HRD.DGROUP.HRM,
HRD.DGROUP.HRP, HRD.DGROUP.HRD, HRD.DGROUP.MEDI, HRD.DGROUP.CONV,
HRD.DGROUP.OUT, HRD.DGROUP.OVR, HRD.DGROUP.PF10, HRD.DGROUP.PF25, HRD.DGROUP.SWF,
HRD.DGROUP.GASS, HRD.DGROUP.GASD, HRD.DGROUP.PROD, HRD.DGROUP.ATTN,
HRD.DGROUP.FRID, HRD.DGROUP.SUBSD, HRD.DGROUP.ENT, HRD.DGROUP.INSUR
FROM HRD.EMPLOYEE, HRD.DGROUP
WHERE (HRD.EMPLOYEE.GROUPID=HRD.DGROUP.GROUPID)
