CREATE OR REPLACE FUNCTION INCOMETAX(iname varchar2,BSAL NUMBER) RETURN NUMBER IS
iTaxP NUMBER(12,2):=0;
TMPBSAL NUMBER(12,2);
	CURSOR CUR_iTAXDETAIL IS 
		SELECT RANGE2,ITAXP FROM ITAXDETAIL,ITAX
		WHERE(ITAXDETAIL.CATID=ITAX.CATID) AND (RANGE2<BSAL AND STATUS=1 
		AND UPPER(trim(INTERNALNAME))=upper(trim(iname))) 
		AND  ACTDATE = (SELECT MAX(ACTDATE) FROM ITAX)
		ORDER BY RANGE2 DESC ;
CUR_ITAXDETAIL_IDX NUMBER;
BEGIN
	TMPBSAL := BSAL;
	FOR  CUR_ITAXDETAIL_IDX  IN CUR_iTAXDETAIL LOOP
	iTAXP:=iTAXP+(TMPBSAL-NVL(CUR_ITAXDETAIL_IDX.RANGE2,0))/100*CUR_ITAXDETAIL_IDX.ITAXP;
	TMPBSAL := CUR_ITAXDETAIL_IDX.RANGE2;
	END LOOP;
RETURN iTAXP/12;			
END;